# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26d12767cfd25a34d8b7977cf67e83af7830b0c77382d02193546440b7db991694bfb200291df09fa86cce14c12fdcf00710443491c37fd68dd649c01d4671ef

test:
  secret_key_base: f39453dd2ac458f58957fb3c1426028e5c4a8394028852a54fbd6a8e019119d6768de45e4a0839a0a1acc31512ffb46895c8175cb73219129556190c5c78b54b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
